export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILED = "ADD_REVIEW_FAILED";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAILED = "DELETE_REVIEW_FAILED";


export const BOOK_REVIEW_LIST_REQUEST = "BOOK_REVIEW_LIST_REQUEST";
export const BOOK_REVIEW_LIST_SUCCESS = "BOOK_REVIEW_LIST_SUCCESS";
export const BOOK_REVIEW_LIST_FAILED = "BOOK_REVIEW_LIST_FAILED";

export const USER_REVIEW_LIST_REQUEST = "USER_REVIEW_LIST_REQUEST";
export const USER_REVIEW_LIST_SUCCESS = "USER_REVIEW_LIST_SUCCESS";
export const USER_REVIEW_LIST_FAILED = "USER_REVIEW_LIST_FAILED";