export const SEARCH_BOOKS_REQUEST = "SEARCH_BOOKS_REQUEST";
export const SEARCH_BOOKS_SUCCESS = "SEARCH_BOOKS_SUCCESS";
export const SEARCH_BOOKS_FAILED = "SEARCH_BOOKS_FAILED";

export const SINGLE_BOOK_REQUEST = "SINGLE_BOOK_REQUEST";
export const SINGLE_BOOK_SUCCESS = "SINGLE_BOOK_SUCCESS";
export const SINGLE_BOOK_FAILED = "SINGLE_BOOK_FAILED";

