export const SEARCH_BOOKS_REQUEST = "SEARCH_BOOKS_REQUEST";
export const SEARCH_BOOKS_SUCCESS = "SEARCH_BOOKS_SUCCESS";
export const SEARCH_BOOKS_FAILED = "SEARCH_BOOKS_FAILED";

export const SINGLE_BOOK_REQUEST = "SINGLE_BOOK_REQUEST";
export const SINGLE_BOOK_SUCCESS = "SINGLE_BOOK_SUCCESS";
export const SINGLE_BOOK_FAILED = "SINGLE_BOOK_FAILED";

export const ADD_BOOK_LIBRARY_REQUEST = "ADD_BOOK_LIBRARY_REQUEST";
export const ADD_BOOK_LIBRARY_SUCCESS = "ADD_BOOK_LIBRARY_SUCCESS";
export const ADD_BOOK_LIBRARY_FAILED = "ADD_BOOK_LIBRARY_FAILED";

export const REMOVE_BOOK_LIBRARY_REQUEST = "REMOVE_BOOK_LIBRARY_REQUEST";
export const REMOVE_BOOK_LIBRARY_SUCCESS = "REMOVE_BOOK_LIBRARY_SUCCESS";
export const REMOVE_BOOK_LIBRARY_FAILED = "REMOVE_BOOK_LIBRARY_FAILED";


